on:
  push:
    branches:     # Matching branch pattern
    - feature/*
    - feature*
    - feature-1

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: wei/pull-request@master
      env:
        SOURCE_BRANCH: "feature-1"
        DESTINATION_BRANCH: "master"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '-m "Pull $SOURCE_BRANCH into $DESTINATION_BRANCH"'
