on:
  push:
    branches:
    - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request      
      uses: repo-sync/pull-request@83f735758c06a61115431a8e77b426d4e13b7094
      with:
        destination_branch: "feature-2"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: Test 1
        pr_body: |
          :crown: *An automated PR*

          Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)
