on:
  push:
    branches:
    - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2.9-alpha.2
      with:
        destination_branch: "feature-2"
        pr_title: Test 2
        pr_body: |
          :crown: *An automated PR*

          Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)
