on:
  push:
    branches:
    - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request      
      uses: repo-sync/pull-request@a7614b9625d2222a0616f23ebca0c93fdf792d45
      with:
        destination_branch: "feature-2"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: Test 1
        pr_body: |
          :crown: *An automated PR*

          Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)
