on:
  push:
    branches:
    - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request      
      uses: docker://ghcr.io/repo-sync/pull-request:v2.8@sha256:cf4c56e7a11cb9eae670c2422d9ccb6fa87e34e2a7ceafe1270ad0be872c318e
      with:
        destination_branch: "feature-2"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: Test 1
        pr_body: |
          :crown: *An automated PR*

          Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)
