on:
  push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "pr-destination"
        pr_title: "master -> pr-destination"
        pr_reviewer: "wei"
        pr_assignee: "wei"
        pr_label: "test label"
        github_token: ${{ secrets.GITHUB_TOKEN }}
