on:
  push:
    branches:
    - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "feature-2"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: Test 1
        pr_body: "
A Line 1\n
B Line 2\n
C Line 3"
