on: push

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          #GITHUB_CONTEXT: ${{ toJson(github) }}
          WHICH_BRANCH: ${{ secrets.WHICH_BRANCH }}
        run: echo "$WHICH_BRANCH"
